title: Sotiris Touliopoulos
logo: /img/touliopoulos_profil.jpg
#description:
show_downloads: true
theme: jekyll-theme-minimal

linkedin: https://www.linkedin.com/in/sotiris-touliopoulos-91769920a/
github: https://github.com/SotirisTouliopoulos

