title: Sotiris Touliopoulos
logo: /img/touliopoulos_profil.jpg
#description:
show_downloads: true
theme: jekyll-theme-minimal

social_links:
  - name: LinkedIn
    url: https://www.linkedin.com/in/sotiris-touliopoulos-91769920a/
    icon: fab fa-linkedin
  - name: GitHub
    url: https://github.com/SotirisTouliopoulos
    icon: fab fa-github


